export GOTRUE_JWT_SECRET="local-test-secret-at-least-32-characters-long!!"
export GOTRUE_JWT_EXP=3600 GOTRUE_JWT_AUD=authenticated GOTRUE_JWT_DEFAULT_GROUP_NAME=authenticated GOTRUE_JWT_ADMIN_ROLES=service_role
export GOTRUE_DB_DRIVER=postgres DB_NAMESPACE=auth DATABASE_URL="postgres://supabase_auth_admin:root@localhost:5499/gotrue?sslmode=disable&host=/tmp/pgtest"
export API_EXTERNAL_URL="http://localhost:9998/auth/v1" GOTRUE_API_HOST=127.0.0.1 PORT=9999
export GOTRUE_SITE_URL="http://localhost:4177" GOTRUE_URI_ALLOW_LIST="http://localhost:4177/**,http://localhost:4177"
export GOTRUE_DISABLE_SIGNUP=true GOTRUE_EXTERNAL_EMAIL_ENABLED=true GOTRUE_MAILER_AUTOCONFIRM=false
export GOTRUE_SMTP_HOST=127.0.0.1 GOTRUE_SMTP_PORT=2525 GOTRUE_SMTP_USER= GOTRUE_SMTP_PASS= GOTRUE_SMTP_ADMIN_EMAIL=noreply@familypilot.test GOTRUE_SMTP_SENDER_NAME=FamilyPilot GOTRUE_SMTP_MAX_FREQUENCY=1s
export GOTRUE_MAILER_URLPATHS_CONFIRMATION=/auth/v1/verify GOTRUE_MAILER_URLPATHS_INVITE=/auth/v1/verify GOTRUE_MAILER_URLPATHS_RECOVERY=/auth/v1/verify GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE=/auth/v1/verify
export GOTRUE_MAILER_OTP_EXP=3600 GOTRUE_PASSWORD_MIN_LENGTH=10 GOTRUE_EXTERNAL_ANONYMOUS_USERS_ENABLED=false
export GOTRUE_RATE_LIMIT_EMAIL_SENT=100 GOTRUE_SECURITY_REFRESH_TOKEN_REUSE_INTERVAL=0 GOTRUE_LOG_LEVEL=info
