module.exports = {
  id: 'fp-google-ChIJrcFVE-YNdkgRJQPxAxaTnMY', name: 'Gunnersbury Park', category: 'park', site: 'visitgunnersbury.org',
  sources: [
    { host: 'visitgunnersbury.org', role: 'own site', status: 'dead', http: 404, observedOn: '2026-10-08', retry: 'never automatically',
      note: 'The link from the venue\'s own site to its park page leads to a page that no longer exists.',
      alternatives: ['The museum\'s accessibility and visit pages (read)', 'A person who has visited'] },
  ],
  facts: [
    { sec: 'activities', key: 'park-museum-lake', kind: 'provision', label: 'Park, museum and boating lake',
      t: 'A park with a museum and a boating lake, and events for children and families. No age is given.', u: '/',
      q: 'wandering around the museum or boating on the lake - there\'s plenty to enjoy at Gunnersbury.' },
    { sec: 'activities', key: 'age-specific', st: 'unknown', t: 'Which ages the park, museum and lake suit: not stated.', n: 'No playground, and no age for any permanent activity, is described on the pages read.' },
    { sec: 'pushchair', key: 'terrain', gtk: true, v: 'tarmac, uneven in places', t: 'A network of tarmac paths; because the park is a natural environment, paths may be uneven in places.', u: '/plan-your-visit',
      q: 'There is a network of tarmac paths within the park at Gunnersbury. However, because the park is a natural environment, paths may be uneven in places.' },
    { sec: 'toilets', key: 'toilets', v: 'yes', t: 'A park toilet block near the museum, and a toilet in the museum.', u: '/plan-your-visit',
      q: 'There is also an accessible toilet in the park toilet block, which is located near the museum.' },
    { sec: 'toilets', key: 'accessibleToilet', v: 'yes', t: 'Accessible toilets in the museum (ground floor, no RADAR key) and the park toilet block.', u: '/plan-your-visit',
      q: 'There is an accessible toilet in the museum. There is also an accessible toilet in the park toilet block, which is located near the museum.' },
    { sec: 'toilets', key: 'babyChanging', st: 'unknown', t: 'Baby changing: not stated on the pages read.', n: 'Only accessible toilets are described.' },
    { sec: 'transport', key: 'station', v: 'Acton Town', t: 'Ten minutes\' walk from Acton Town (Piccadilly, District) or South Ealing; Kew Bridge rail; E3, 65 and H91 buses.', u: '/plan-your-visit',
      q: 'Acton Town Tube Station Piccadilly and District lines Turn left when you leave the station and walk along Gunnersbury Lane for about ten minutes' },
    { sec: 'transport', key: 'parking', v: 'yes', t: 'Two car parks, charged at all times: £1 for 30 minutes to 1 hour, £1 an hour after; Blue Badge holders free.', u: '/plan-your-visit',
      q: 'There are two car parks available at Gunnersbury.' },
    { sec: 'transport', key: 'blueBadge', v: 'yes', t: 'Free designated disabled parking in both car parks.', u: '/plan-your-visit',
      q: 'Designated disabled parking for blue badge holders can be found in both car parks and parking is free.' },
    { sec: 'food', key: 'cafe', v: 'yes', t: 'The Pure in the Park café: weekdays 7am to 5pm, weekends 7am to 6pm.', u: '/plan-your-visit',
      q: 'Café Monday to Friday: 7am to 5pm Weekends: 7am to 6pm' },
    { sec: 'play', key: 'playground', st: 'unknown', t: 'A children\'s playground: not mentioned on the pages read.', n: 'A large park is likely to have one, but nothing read says so.' },
    { sec: 'access', key: 'wheelchair', v: 'yes', t: 'The museum lift serves all galleries and suits wheelchairs, including small motorised ones.', u: '/plan-your-visit',
      q: 'Inside, a self-operated lift serves all the galleries and is suitable for wheelchairs, including small motorised ones.' },
    { sec: 'access', key: 'stepFree', v: 'yes', t: 'Step-free access throughout the museum (some ramps and slopes); a lift to all levels; a manual wheelchair to borrow.', u: '/museum/accessibility',
      q: 'Step-free access is available throughout the museum, with some ramps and slopes' },
    { sec: 'access', key: 'relaxed', gtk: true, v: 'yes', t: 'Relaxed sessions every half term; quieter times are weekdays 2 to 4pm, weekend mornings 10 to 12.', u: '/museum/accessibility',
      q: 'We offer Relaxed Sessions every half term.' },
    { sec: 'opening', key: 'hours', v: 'Park 7:00-dusk; Museum Tue-Sun 10:00-16:30', t: 'Park open daily from 7am until dusk; museum Tuesday to Sunday 10am to 4.30pm (closed Mondays).', u: '/plan-your-visit',
      q: 'Opening Hours Museum Tuesday-Sunday 10am to 4:30pm Park Daily between 7am until dusk', conflict: 'the provider (Google) hours, which show the park as open 24 hours' },
    { sec: 'pricing', key: 'free', v: 'free', t: 'The museum and park are free to enter; car parking is charged.', u: '/plan-your-visit', q: 'Our museum and park are free entry .' },
    { sec: 'considerations', key: 'dogs', v: 'no dogs in museum', t: 'No dogs in the museum except assistance dogs.', u: '/plan-your-visit',
      q: 'Please note we do not allow dogs into the museum, with the exception of Assistance Dogs.' },
  ],
};
