module.exports = {
  id: 'fp-google-ChIJV_iXMtcadkgRqBI84CY_crE', name: 'London Zoo', category: 'zoo', site: 'londonzoo.org',
  facts: [
    { sec: 'activities', key: 'zootown', kind: 'provision', ages: [0, 108], label: 'ZooTown: indoor role-play adventure, best for up to 8',
      t: 'ZooTown is an indoor role-play adventure aimed at children up to 8; every child is welcome. Book online; £1 per child for non-members.', u: '/plan-your-visit/frequently-asked-questions',
      q: ['ZooTown is a brand new indoor role play adventure for kids in the heart of London Zoo aimed at children aged up to 8.', 'Silver members and non-members pay £1 per child'] },
    { sec: 'activities', key: 'animal-talks', kind: 'programme', label: 'Daily animal talks',
      t: 'Daily animal talks and events (no age given).', u: '/plan-your-visit',
      q: 'Find out more about our exciting upcoming events schedule, our enlightening daily animal talks' },
    { sec: 'pushchair', key: 'hire', gtk: true, v: 'yes', t: 'Pushchairs to hire from the gift shop: single £10, double £15, plus a £15 refundable deposit (card only).', u: '/plan-your-visit/frequently-asked-questions',
      q: 'Pushchairs are available to hire from the gift shop. Our single buggies cost £10 and double buggies cost £15 to hire.' },
    { sec: 'pushchair', key: 'allowed', st: 'hypothesis', t: 'Own pushchairs are probably welcome.', n: 'Pushchair hire implies pushchairs are used, but no page read says visitors may bring their own.', u: '/plan-your-visit/frequently-asked-questions', q: 'Pushchairs are available to hire from the gift shop.' },
    { sec: 'toilets', key: 'accessibleToilet', v: 'yes', t: 'Accessible toilets around the zoo and a Changing Places toilet at Animal Adventure.', u: '/plan-your-visit/accessibility',
      q: 'As well as our changing place toilet, we also have a number of accessible toilets around the Zoo.' },
    { sec: 'toilets', key: 'toilets', v: 'yes', t: 'Accessible toilets around the zoo: opposite Tiny Giants, next to the Reptile House, near the main entrance next to the African Aviary, and at The Terrace Restaurant.', u: '/plan-your-visit/accessibility',
      q: 'we also have a number of accessible toilets around the zoo. These are located: Opposite Tiny Giants Next to the Reptile House Near main entrance next to African Aviary The Terrace Restaurant',
      n: 'Derived: accessible toilets are toilets. General toilet blocks are not described.' },
    { sec: 'toilets', key: 'babyFeeding', v: 'yes', t: 'A breastfeeding room and quiet areas; feeding is welcome everywhere.', u: '/plan-your-visit/accessibility',
      q: 'For added privacy, quiet areas and a breastfeeding room are also available.' },
    { sec: 'toilets', key: 'babyChanging', st: 'unknown', t: 'Baby changing: not stated on the pages read.', n: 'The pages read name a Changing Places toilet and accessible toilets but not baby-changing tables.', gap: { venue: 'London Zoo', anchor: 'Accessibility' } },
    { sec: 'transport', key: 'station', v: 'Camden Town', t: 'Camden Town (Northern line) is the nearest Tube: a 16 minute, 0.8 mile walk. Regent\'s Park (24 minutes) and the 274 and 88 buses also serve it.', u: '/plan-your-visit/how-to-get-to-london-zoo',
      q: ['By Tube Camden Town (16 mins / 0.8 miles walk from the Zoo) Camden Town station (Northern Line) is the nearest Underground station to the Zoo.', 'Regent\'s Park (24 mins / 1.2 miles walk)', 'take the 274 bus northbound', 'take the 88 bus northbound'] },
    { sec: 'transport', key: 'parking', v: 'yes', t: 'Zoo car park: £16 in term time, £17.50 at weekends and in bank or school holidays, paid on the day.', u: '/plan-your-visit/frequently-asked-questions',
      q: 'Parking is available in the Zoo’s car park at a cost of £16 in term time or £17.50 on weekends and bank or school holidays, payable on the day.' },
    { sec: 'transport', key: 'blueBadge', v: 'yes', t: 'A disabled bay at the entrance; Blue Badge holders can also park on the Outer Circle for up to four hours.', u: '/plan-your-visit/accessibility',
      q: 'There is a disabled parking bay in front of the entrance to the zoo, disabled visitors can also park on the Outer Circle for up to four hours with a Blue Badge.' },
    { sec: 'food', key: 'cafe', v: 'yes', t: 'The Terrace Restaurant, Peckish Parrot Café, a Barista Bar and kiosks.', u: '/plan-your-visit/opening-times',
      q: 'Coffees and hot drinks are available from our Barista Bar, next to The Terrace Restaurant , from 10am until the Zoo closes.' },
    { sec: 'food', key: 'picnic', v: 'yes', t: 'Outdoor picnic benches.', u: '/plan-your-visit/food-and-drink', q: 'Outdoor picnic benches are available.' },
    { sec: 'play', key: 'playground', st: 'unknown', t: 'An outdoor playground: not stated on the pages read.', n: 'ZooTown is the indoor play space.' },
    { sec: 'access', key: 'wheelchair', v: 'yes', t: 'Most of the zoo is accessible for wheelchair users and those with limited mobility.', u: '/plan-your-visit/accessibility',
      q: 'However, most of the Zoo is accessible for wheelchair users and those with limited mobility.' },
    { sec: 'access', key: 'steep-slopes', gtk: true, v: 'no', scope: 'area', t: 'The slopes to the two tunnels are steep (relevant to pushchairs).', u: '/plan-your-visit/accessibility',
      q: 'Please note that the slopes leading to the two tunnels in the Zoo are steep.' },
    { sec: 'opening', key: 'hours', gtk: true, v: '10:00 open; closing 17:00 until 23 Oct, then 16:00', t: 'Opens 10am. Last entry 4pm and closing 5pm until 23 October; last entry 3pm and closing 4pm from 24 October to 12 February.', u: '/plan-your-visit/opening-times',
      q: 'Dates Opening Last Entry Closing 3 September - 23 October 2026 10am 4pm 5pm 24 October 2026 - 12 February 2027 10am 3pm 4pm', conflict: 'the provider (Google) hours, which show 10am to 5pm every day and will be wrong from 24 October' },
    { sec: 'pricing', key: 'under3', v: 'free', t: 'Children under 3 go free.', u: '/plan-your-visit/frequently-asked-questions',
      q: 'Children under the age of 3 years are entitled to free entry to both of our Zoos.' },
    { sec: 'pricing', key: 'variable', v: { adult16to64: '£27.70 to £34.50', child3to15: '£19.40 to £24.10' }, t: 'Online advance prices (before 10am on the day, no donation): adult £27.70 to £34.50 and child (3 to 15) £19.40 to £24.10 depending on the day; gate prices are higher.', u: '/plan-your-visit/london-zoo-tickets',
      q: ['Online advance ticket prices without donation Off Peak Weekday Standard Standard Weekend Peak Adult (age 16-64) £ 27.70 £ 31.80 £ 33.60 £ 34.50 Child (age 3-15) £ 19.40 £ 22.20 £ 23.50 £ 24.10', 'the prices below apply for tickets bought at the entrance, or online from 10am on the date of the visit'],
      n: 'Price depends on which of four day types the visit falls on, and the page does not say which dates are which. A total for a family is therefore not computed.' },
    { sec: 'considerations', key: 'supervision', v: 'under 16 with an adult', t: 'Children under 16 are not admitted without an adult.', u: '/plan-your-visit/opening-times',
      q: 'Children under 16 will not be admitted without an adult.' },
  ],
};
