import type { Ionicons } from '@expo/vector-icons';

import type { BenefitIconKind } from '@/src/components/onboarding/BenefitIcon';
import type { PhotoSlotCategory } from '@/src/components/ui';

/**
 * The Welcome composition, from the approved frame 166:128 (852 x 1846 px: a 393 pt phone drawn at
 * 2.168x, so pt = px / 2.168). The photograph cut-outs' outlines, positions and sizes are the frame's
 * own mask vectors (`WELCOME_CUTOUTS` in `src/assets/art/figma-art.ts`, generated by
 * `scripts/build-art.mjs`); the decorative stickers are its artwork layer (`WELCOME_ART`). The
 * photographs themselves in the frame are review-only crops: the app fills each slot from
 * `src/assets/welcome-photos.ts` or, until a licensed photograph exists, the category gradient.
 *
 * Kept out of the screen so a test can hold it to the rules the brief set for the slots: nothing is
 * interactive, nothing is a stock photo.
 */
export const WELCOME_FRAME_WIDTH = 852;
/** The OS status bar the frame draws above the app (59 pt on the phone it was drawn on). */
export const WELCOME_FRAME_INSET = 59;
/** Frame pixels to points at the 393 pt reference width. */
export const WELCOME_PX = 393 / WELCOME_FRAME_WIDTH;
/** The collage, brand mark, headline and subtitle end here; the first benefit card starts below (frame y 1238). */
export const WELCOME_STAGE_END_PX = 1236;

export interface WelcomeSlot {
  id: string;
  /** The editorial subject the slot is reserved for, so a photograph is sourced for it later. */
  subject: string;
  category: PhotoSlotCategory;
  icon: keyof typeof Ionicons.glyphMap;
}

/** The seven slots, in the frame's own order. Geometry lives in `WELCOME_CUTOUTS`, keyed by id. */
export const WELCOME_COLLAGE = {
  slots: [
    { id: 'zoo', subject: 'giraffe at a zoo', category: 'zoo', icon: 'paw-outline' },
    { id: 'farm', subject: 'child stroking a rabbit at a farm', category: 'farm', icon: 'flower-outline' },
    { id: 'cafe', subject: 'coffee and a croissant', category: 'cafe', icon: 'cafe-outline' },
    { id: 'crafts', subject: 'child painting pottery', category: 'activity', icon: 'color-palette-outline' },
    { id: 'soft-play', subject: 'toddler on a soft-play frame', category: 'soft_play', icon: 'happy-outline' },
    { id: 'puddles', subject: 'yellow wellies in a puddle', category: 'park', icon: 'rainy-outline' },
    { id: 'aquarium', subject: 'penguin at an aquarium', category: 'beach', icon: 'water-outline' },
  ] as const satisfies readonly WelcomeSlot[],
} as const;

export const WELCOME_BENEFITS: readonly {
  icon: BenefitIconKind;
  title: string;
  subtitle: string;
}[] = [
  { icon: 'sprout', title: 'Days out & activities', subtitle: 'Find places that actually suit your family.' },
  { icon: 'people', title: 'Personalised recommendations', subtitle: "Based on your children's ages and needs." },
  { icon: 'sparkles', title: 'Less planning, more family time', subtitle: 'Get ideas, itineraries and helpful tips.' },
];
