/**
 * Turns the decorative artwork exported from the APPROVED Figma frames into the TypeScript modules the
 * app draws it from.
 *
 * Each source SVG in src/assets/art/ is a Figma export of one decorative layer (Home 230:133, Explore
 * 296:133 / 296:136, Welcome 172:128; see docs/FIGMA_APPROVED_FRAMES.md). Figma wraps an exported
 * layer in its parent frame (page background, clip path); this keeps only the artwork group, in the
 * frame's own coordinates, so the app can place any horizontal slice of it by cropping the viewBox.
 *
 * Usage: node scripts/build-art.mjs
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const DIR = join(process.cwd(), 'src', 'assets', 'art');
const SOURCES = [
  ['explore-behind.svg', 'EXPLORE_ART_BEHIND', 'Decorative artwork'],
  ['explore-front.svg', 'EXPLORE_ART_FRONT', 'Decorative artwork'],
  ['home-art.svg', 'HOME_ART', 'Decorative artwork'],
  ['welcome-art.svg', 'WELCOME_ART', 'Decorative artwork'],
];

/** Index just past the `</g>` that closes the `<g` opening at `start`. */
function endOfGroup(xml, start) {
  let depth = 0;
  const tag = /<g[\s>]|<\/g>/g;
  tag.lastIndex = start;
  let m;
  while ((m = tag.exec(xml))) {
    if (m[0].startsWith('</')) {
      depth -= 1;
      if (depth === 0) return m.index + 4;
    } else {
      depth += 1;
    }
  }
  throw new Error('unbalanced group');
}

let out = `/**
 * GENERATED by scripts/build-art.mjs from the decorative layers of the approved Figma frames
 * (docs/FIGMA_APPROVED_FRAMES.md). Do not edit by hand: change the Figma frame, re-export, rebuild.
 *
 * Coordinates are the frame's own (852-853 wide: a 393pt phone at 2.168x). \`ScreenArt\` scales and crops.
 */
export interface ArtSource {
  width: number;
  height: number;
  /** Inner SVG markup, in frame coordinates. */
  body: string;
}

`;

for (const [file, name, groupPrefix] of SOURCES) {
  const xml = readFileSync(join(DIR, file), 'utf8');
  const size = /<svg width="(\d+)" height="(\d+)"/.exec(xml);
  const start = xml.search(new RegExp(`<g id="${groupPrefix}`));
  if (!size || start < 0) throw new Error(`${file}: artwork group not found`);
  let body = xml.slice(start, endOfGroup(xml, start));
  // Layer names are for Figma, not for the app.
  body = body.replace(/ id="[^"]*"/g, '');
  out += `export const ${name}: ArtSource = {\n  width: ${size[1]},\n  height: ${size[2]},\n  body: ${JSON.stringify(body)},\n};\n\n`;
}

// The seven Welcome photograph cut-outs: the approved frame's mask vectors (169:133 ... 169:151),
// exported as SVG into src/assets/art/masks/. Each is keyed by the collage slot it shapes, with the
// node's own position and size in the frame (852 wide). Figma exports a mask with a margin of about
// 0.5 for its stroke (more on y for two of them), measured here as the offset between the SVG's
// first point and the node's own vectorPaths first point, and the path is shifted back by it.
const CUTOUTS = [
  // [slot, file, x, y, width, height, offsetY]
  ['zoo', 'giraffe', 633.7007, 128.884, 266.299, 438.116, 0.5],
  ['farm', 'bunny', -20, 470, 376.563, 377.226, 1.08],
  ['cafe', 'coffee', 344.6935, 582, 332.107, 347.11, 0.5],
  ['crafts', 'painting', 667, 570, 233, 413, 0.5806],
  ['soft-play', 'softplay', -20, 841, 345.238, 310.75, 0.5],
  ['puddles', 'puddle', 312.6369, 906.6445, 297.465, 280.809, 0.4994],
  ['aquarium', 'penguin', 611.0249, 972.9009, 288.975, 253.099, 0.5],
];
out += `export interface CutoutShape {
  /** Position of the cut-out in the frame, in frame pixels. */
  x: number;
  y: number;
  /** Its own size, in frame pixels. */
  width: number;
  height: number;
  /** The outline in the cut-out's own coordinates (0,0 to width,height). */
  d: string;
}

export const WELCOME_CUTOUTS: Record<string, CutoutShape> = {\n`;
for (const [slot, file, x, y, width, height, offsetY] of CUTOUTS) {
  const svg = readFileSync(join(DIR, 'masks', `${file}.svg`), 'utf8');
  const path = /<path[^>]* d="([^"]+)"/.exec(svg);
  if (!path) throw new Error(`${file}: mask path not found`);
  // Every command is absolute (M, C, L, H, V, Z), so the shift is per coordinate: x, then y.
  // H takes one x; V takes one y; the rest take x y pairs.
  let d = '';
  for (const part of path[1].match(/[A-Za-z]|-?\d*\.?\d+(?:e-?\d+)?/g)) {
    d += part;
  }
  const out2 = [];
  let cmd = '';
  let k = 0;
  for (const tok of path[1].match(/[A-Za-z]|-?\d*\.?\d+(?:e-?\d+)?/g)) {
    if (/[A-Za-z]/.test(tok)) {
      cmd = tok;
      k = 0;
      out2.push(tok);
      continue;
    }
    const isY = cmd === 'V' || (cmd !== 'H' && k % 2 === 1);
    out2.push((Number(tok) - (isY ? offsetY : 0.5)).toFixed(2));
    k += 1;
  }
  d = out2.join(' ').replace(/ ([A-Za-z]) /g, '$1').replace(/([A-Za-z]) /g, '$1').replace(/ ([A-Za-z])/g, '$1');
  out += `  ${JSON.stringify(slot)}: { x: ${x}, y: ${y}, width: ${width}, height: ${height}, d: ${JSON.stringify(d)} },\n`;
}
out += '};\n\n';

writeFileSync(join(process.cwd(), 'src', 'assets', 'art', 'figma-art.ts'), out.trimEnd() + '\n');
console.log('wrote src/assets/art/figma-art.ts');
