#!/usr/bin/env node
/**
 * Writes docs/pilot/RANKING_INVESTIGATION.md from the output of the ranking harness
 * (src/__tests__/pilot-ranking.analysis.test.ts). The numbers are the app's own `rankForFamily`; the prose states what they mean.
 *
 *   PILOT_FIXTURE_DIR=... PILOT_RANK_OUT=/tmp/rank.json npx vitest run src/__tests__/pilot-ranking.analysis.test.ts
 *   node scripts/pilot/ranking-report.cjs /tmp/rank.json ../docs/pilot/RANKING_INVESTIGATION.md
 */
const fs = require('node:fs');
const [, , inFile, outFile] = process.argv;
const d = JSON.parse(fs.readFileSync(inFile, 'utf8'));
const keys = d.households.map((h) => h.key);
const short = (n) => n.replace('Royal Air Force Museum London', 'RAF Museum').replace("Discover Children's Story Centre", 'Discover').replace('Natural History Museum', 'Natural History').replace('Horniman Museum and Gardens', 'Horniman').replace('Mudchute Park and Farm', 'Mudchute').replace('Babylon Park London', 'Babylon Park').replace('Gunnersbury Park', 'Gunnersbury');
const top = (state, k, n = 5) => d.states[state][k].slice(0, n);

const out = [];
const w = (s = '') => out.push(s);

const rank1 = (state) => Object.fromEntries(keys.map((k) => [k, d.states[state][k][0].name]));
const count = (state) => { const c = {}; for (const n of Object.values(rank1(state))) c[short(n)] = (c[short(n)] || 0) + 1; return c; };
const fmtCount = (c) => Object.entries(c).sort((a, b) => b[1] - a[1]).map(([n, v]) => `${n} ${v}/${keys.length}`).join(', ');

const reviewed = (state) => keys.flatMap((k) => d.states[state][k].filter((v) => v.enrichment !== 'provider_only'));
const distinct = (state, f) => [...new Set(reviewed(state).map((v) => v.factors[f]))].sort((a, b) => a - b);

w('# Why Home keeps recommending the RAF Museum, and what would change it');
w();
w('Generated by `scripts/pilot/ranking-report.cjs` from the app\'s own ranking (`rankForFamily`, the function Home uses) run over the ten pilot venues for nine different households, in three evidence states: **before** (what production serves today for these venues), **afterAuto** (adding only facts that need no human), **after** (adding every proposed fact and rule, assuming a person approves them). Nothing in the app was changed to produce the tables in sections 1 to 3. Section 4 is a set of *proposals* computed beside the app; no ranking code reads them.');
w();
w('## Households');
w();
w('| | Household | Home | Drive limit |');
w('|---|---|---|---|');
for (const h of d.households) w(`| ${h.key} | ${h.label} | ${h.home} | ${h.limit === null ? 'none' : h.limit + ' min'} |`);
w();

w('## 1. What decides the order');
w();
w('Home orders by one number, the Family Fit score, then by drive time. The score is a weighted average of five factors (age 0.25, accessibility 0.15, distance 0.15, budget 0.10, facilities 0.15). The verdict badge (Excellent, Good, Possible, Poor) is a label: **it does not move a venue in the order**.');
w();
w('Across the reviewed ten venues and nine households, in the `after` state, the distinct values each factor took:');
w();
w('| Factor | Weight | Distinct values | Reading |');
w('|---|---|---|---|');
const row = (f, wt, reading) => w(`| ${f} | ${wt} | ${distinct('after', f).join(', ')} | ${reading} |`);
row('ageSuitability', '0.25', 'Constant. No venue carries a recommended age range, so every venue gets the neutral 75 for every household. A quarter of the weight differentiates nothing.');
row('budgetFit', '0.10', 'Constant. No venue has an estimated-spend tier, so every venue scores alike.');
row('distance', '0.15', 'Saturates. With a stated limit, anything within half of it scores 98, so most venues tie on distance for most households.');
row('accessibility', '0.15', 'Only the buggy rating moves it (90 good, 74/68 mixed, 70 nothing known). Wheelchair, step-free and mobility-aid evidence are not scored at all.');
row('facilitiesMatch', '0.15', 'The one factor that varies: the more facilities a venue has confirmed (toilets, café, parking, baby changing), the higher it scores.');
w();
w('So the order is, in effect, **who has the most confirmed facility claims and a positive buggy statement, then who is nearest**. That is evidence coverage. It is not a judgement about which household a venue suits.');
w();
w(`Rank 1 in the three states: before: ${fmtCount(count('before'))}; afterAuto: ${fmtCount(count('afterAuto'))}; after: ${fmtCount(count('after'))}.`);
w();

w('## 2. The top five for each household');
for (const state of ['before', 'after']) {
  w();
  w(`### ${state === 'before' ? 'Before: what production serves today for these ten venues' : 'After: every proposed fact and rule approved'}`);
  w();
  w('| | #1 | #2 | #3 | #4 | #5 |');
  w('|---|---|---|---|---|---|');
  for (const k of keys) w(`| ${k} | ${top(state, k).map((v) => `${short(v.name)} ${v.score}${v.verdict === 'poor' ? ' ⚠' : ''}`).join(' | ')} |`);
}
w();
w('⚠ marks a venue whose own verdict for that household is Poor (a confirmed conflict with something the household needs).');
w();
const find = (state, k, re) => d.states[state][k].find((v) => re.test(v.name));
const gap = (state) => {
  const raf = find(state, 'A', /^Royal Air Force/);
  const nextBest = d.states[state].A.find((v) => !/^Royal Air Force/.test(v.name));
  const diffs = ['ageSuitability', 'accessibility', 'distance', 'budgetFit', 'facilitiesMatch'].filter((f) => raf.factors[f] !== nextBest.factors[f]).map((f) => `${f} ${raf.factors[f]} against ${nextBest.factors[f]}`);
  return `${state}: the RAF Museum ${raf.score} against ${short(nextBest.name)} ${nextBest.score}; the factors that differ are ${diffs.join(', ') || 'none'}.`;
};
w('### Reading one household closely');
w();
w('Household A (a four-year-old and a baby with a buggy). ' + gap('before') + ' ' + gap('after'));
w();
w('In the `before` state the RAF Museum is the only venue with a positive buggy statement, which is worth 20 points of the accessibility factor (90 against 70). In the `after` state the Science Museum also gets one ("buggies are allowed in the galleries"), so the remaining gap is the number of confirmed facilities. In neither state does age, budget or distance separate them.');
w();

w('## 3. Defects, and missing evidence');
w();
w('| # | Finding | Kind | Why |');
w('|---|---|---|---|');
w('| 1 | The age factor never differentiates venues | **Ranking defect** (design) | The evidence exists: reviewed activity readings say what children of an age can do at five of the ten venues (ZooTown up to 8; a baby space for 0 to 2; a playground for 4 to 14). They explain a venue on its page and can earn an Excellent label, but they never reach the score. |');
w('| 2 | A venue that conflicts with a household\'s own stated need can still rank first | **Ranking defect** (design) | Household H needs buggy access; Discover does not allow pushchairs in its play areas. Its verdict is Poor, but the label does not move the order, so it is H\'s #1 in the `after` state. |');
w('| 3 | Mobility-aid and wheelchair households are ranked as if everyone walked | **Ranking defect** (design) | Step-free evidence (lifts, mezzanine gaps) is never scored, and the accessibility factor reads only the buggy rating. |');
w('| 4 | The RAF Museum leads for most households | **Missing evidence**, not a defect | It is the venue with the most confirmed facilities and a buggy statement. The other nine are less well evidenced. Nothing in the formula favours it by name. |');
w('| 5 | Budget is the same for every venue | **Missing evidence** | None of the ten has a spend tier in its metadata. Several pilot profiles hold price evidence, but admission prices are published only through the separate admission review, so this is missing evidence, not a ranking choice. |');
w('| 6 | Nearly everything within half the drive limit ties on distance | Design property | Works as intended for a household with a generous limit; with a tight one (E, H) distance does discriminate. |');
w();

w('## 4. Proposals (not implemented; each needs your decision)');
w();
w('**P1. Let reviewed activity evidence raise the age factor.** For each child, if a permanent provision on the venue\'s own pages covers their age, the age factor moves from the neutral 75 towards the 96 a stated recommended range already earns, in proportion to the share of children covered. A child nothing covers stays at 75: absence of evidence is never evidence against. Programmes on set days do not count. Unreviewed venues are untouched.');
w();
w('**P2. Rank confirmed conflicts below places without one.** A venue whose verdict for this household is Poor ranks after those that are not, whatever its score. Weights unchanged.');
w();
w('The arithmetic below reproduces the app\'s own scores exactly when no proposal is applied (0 mismatches in every venue-household pair where the age factor is unchanged, in all three states), so the differences are the proposals and nothing else.');
w();
for (const state of ['after']) {
  w(`### Top five, current vs P1 vs P1+P2 (${state} state)`);
  w();
  w('| | Current | With P1 | With P1 + P2 |');
  w('|---|---|---|---|');
  const P = d['proposals_' + state];
  for (const k of keys) {
    const f = (list) => list.map((r) => `${short(r.name)} ${r.score}${r.covered.length ? '*' : ''}${r.breach ? '!' : ''}`).join('; ');
    w(`| ${k} | ${f(P[k].base.map((r) => ({ ...r, covered: [] })))} | ${f(P[k].p1)} | ${f(P[k].p1p2)} |`);
  }
  w();
  w('`*` the age factor was raised for at least one child. `!` a confirmed conflict for this household.');
}
w();
const P = d.proposals_after;
const changed = keys.filter((k) => P[k].base[0].name !== P[k].p1p2[0].name).length;
w(`With P1+P2 (ceiling 96) the #1 venue changes for ${changed} of ${keys.length} households (the RAF Museum is #1 today for ${keys.filter((k) => /Royal Air Force/.test(P[k].base[0].name)).length}, and under P1+P2 for ${keys.filter((k) => /Royal Air Force/.test(P[k].p1p2[0].name)).length}).`);
w();
const S = (k) => P[k].sensitivity;
const maxGain = Math.max(...keys.map((k) => S(k).maxGain96));
const maxGainLow = Math.max(...keys.map((k) => S(k).maxGain85));
const topChanges96 = keys.filter((k) => S(k).top96 !== P[k].base[0].name).length;
const topChanges85 = keys.filter((k) => S(k).top85 !== P[k].base[0].name).length;
w('### What to be careful about before approving P1');
w();
w(`- It is a **material scoring change**. At full coverage it adds at most ${maxGain} points to a venue (a ceiling of 85 instead of 96 would add at most ${maxGainLow}), where neighbours differ by 1 to 3, so it reorders the top of the list for any household with a covered child. That is the intent, and the reason it needs your approval.`);
w(`- Sensitivity: the best-ranked venue (excluding confirmed conflicts) differs from today's for ${topChanges96} of ${keys.length} households at a ceiling of 96 and for ${topChanges85} of ${keys.length} at 85. So the ceiling is the dial that decides how far the RAF Museum's lead is overturned.`);
w('- It rests on **reviewed readings that exist for five of the ten venues** (Babylon Park, Battersea, Discover, London Zoo, Science Museum). A venue with a reading is advantaged over an equally good venue nobody has read yet. That is an incentive to review, but also a fairness question while coverage is this thin; widening the reviewed set first would reduce it.');
w('- The proportional rule and the 75 floor are choices. A child nothing covers is neither helped nor harmed.');
w('- Readings lapse after 90 days, so a venue\'s age factor falls back to 75 by itself if its page is not read again.');
w();
w('## 5. What was and was not changed');
w();
w('- Changed (no effect on any score or weight): venue rules reach the planner, Family Fit lines and Venue Detail; a venue closed today by a reviewed rule shows **Closed today**.');
w('- Not changed: the weights, the factor formulas, the order, or the meaning of any verdict.');
fs.writeFileSync(outFile, out.join('\n') + '\n');
console.log(`wrote ${outFile} (${out.length} lines)`);
