import { StyleSheet, useWindowDimensions, View, ViewStyle } from 'react-native';
import { SvgXml } from 'react-native-svg';

import type { ArtSource } from '@/src/assets/art/figma-art';

interface ScreenArtProps {
  art: ArtSource;
  /**
   * The slice of the frame to draw, in the frame's own pixels (the frames are 852-853 wide, a 393pt
   * phone at 2.168x). Cropping by slice lets a screen anchor its upper marks to the top edge and its
   * foot marks to the bottom edge, so a taller phone keeps each mark beside what it decorates instead
   * of stretching the whole canvas.
   */
  from: number;
  to: number;
  /** `top`: the slice keeps its frame distance from the top edge. `bottom`: from the bottom edge. */
  anchor: 'top' | 'bottom';
  /** The width the whole frame is drawn at; the window's, unless the screen caps its composition. */
  width?: number;
  /**
   * Draw only this horizontal slice of the frame (frame pixels), pinned to `align`'s edge. Marks that
   * follow the fixed-size type (beside a heading) and marks that follow the screen's edge (a leaf off
   * the right side) need different scales on a wide phone, so a screen draws them as two slices.
   */
  clipX?: [number, number];
  align?: 'left' | 'right';
  style?: ViewStyle;
  testID?: string;
}

/**
 * The identity's decorative artwork, drawn from the approved Figma frames' own vectors
 * (`src/assets/art/figma-art.ts`, generated by `scripts/build-art.mjs`) at the frame's scale.
 *
 * It follows the rules the references set: it sits on the canvas behind or beside content, never on a
 * control; it ignores the pointer; and it is hidden from assistive technology.
 */
export function ScreenArt({ art, from, to, anchor, width: drawnWidth, clipX, align = 'left', style, testID }: ScreenArtProps) {
  const window = useWindowDimensions();
  const width = drawnWidth ?? window.width;
  const scale = width / art.width;
  const height = (to - from) * scale;
  const [x0, x1] = clipX ?? [0, art.width];
  const layerWidth = (x1 - x0) * scale;
  const xml =
    `<svg xmlns="http://www.w3.org/2000/svg" width="${x1 - x0}" height="${to - from}" ` +
    `viewBox="${x0} ${from} ${x1 - x0} ${to - from}" fill="none">${art.body}</svg>`;
  const position: ViewStyle =
    anchor === 'top' ? { top: from * scale } : { bottom: (art.height - to) * scale };

  return (
    <View
      pointerEvents="none"
      accessibilityElementsHidden
      importantForAccessibility="no-hide-descendants"
      aria-hidden
      testID={testID}
      style={[
        styles.layer,
        clipX ? (align === 'right' ? { right: 0, width: layerWidth } : { left: 0, width: layerWidth }) : styles.fullWidth,
        { height },
        position,
        style,
      ]}
    >
      <SvgXml xml={xml} width={layerWidth} height={height} />
    </View>
  );
}

const styles = StyleSheet.create({
  layer: {
    position: 'absolute',
  },
  fullWidth: {
    left: 0,
    right: 0,
  },
});
