  {
    venueId: 'fp-google-ChIJV_iXMtcadkgRqBI84CY_crE',
    venueName: 'London Zoo',
    kind: 'provision',
    minMonths: 0,
    maxMonthsExclusive: 108,
    label: 'ZooTown: indoor role-play adventure, best suited to children up to 8',
    evidence: {
      url: 'https://www.londonzoo.org/plan-your-visit/frequently-asked-questions',
      retrievedAt: '2026-10-08',
      subjectScope: 'venue_own_subtree',
      excerpt: 'ZooTown is a brand new indoor role play adventure for kids in the heart of London Zoo aimed at children aged up to 8.',
    },
    reviewNotes: 'AI-assisted source verification awaiting founder approval (docs/pilot/beta/verification), not independent human review. Age band is the FAQ\'s \'aimed at children aged up to 8\' (every child is welcome); 8 is read as inside the range. The booking rule is left out because the FAQ contradicts itself; the session fee is not activity evidence.',
  },
  {
    venueId: 'fp-google-ChIJP9oAE0MFdkgR3iKGFKZO1SE',
    venueName: 'Science Museum',
    kind: 'provision',
    minMonths: 36,
    maxMonthsExclusive: 84,
    label: 'The Garden: play-based science in four interactive areas (construction, water, light and sound), recommended for 3 to 6',
    evidence: {
      url: 'https://www.sciencemuseum.org.uk/visit/young-explorers-guide-science-museum',
      retrievedAt: '2026-10-08',
      subjectScope: 'venue_own_subtree',
      excerpt: 'check out one of our family favourites and a must-visit for 3–6-year-olds, The Garden . Discover science through play in four interactive areas—construction, water, light and sound.',
    },
    reviewNotes: 'AI-assisted source verification awaiting founder approval (docs/pilot/beta/verification), not independent human review. The page recommends The Garden for 3 to 6; a school-groups page on the same site gives the same range. \'Hands-on\' and \'gallery\' are not used.',
  },
